Country.create(code: 'AE', name: "United Arab Emirates")
Country.create(code: 'AG', name: "Antigua and Barbuda")
Country.create(code: 'AI', name: "Anguilla")
Country.create(code: 'AL', name: "Albania")
Country.create(code: 'AM', name: "Armenia")
Country.create(code: 'AO', name: "Angola")
Country.create(code: 'AR', name: "Argentina")
Country.create(code: 'AT', name: "Austria")
Country.create(code: 'AU', name: "Australia")
Country.create(code: 'AZ', name: "Azerbaijan")
Country.create(code: 'BB', name: "Barbados")
Country.create(code: 'BE', name: "Belgium")
Country.create(code: 'BF', name: "Burkina Faso")
Country.create(code: 'BG', name: "Bulgaria")
Country.create(code: 'BH', name: "Bahrain")
Country.create(code: 'BJ', name: "Benin")
Country.create(code: 'BM', name: "Bermuda")
Country.create(code: 'BN', name: "Brunei")
Country.create(code: 'BO', name: "Bolivia")
Country.create(code: 'BR', name: "Brazil")
Country.create(code: 'BS', name: "Bahamas")
Country.create(code: 'BT', name: "Bhutan")
Country.create(code: 'BW', name: "Botswana")
Country.create(code: 'BY', name: "Belarus")
Country.create(code: 'BZ', name: "Belize")
Country.create(code: 'CA', name: "Canada")
Country.create(code: 'CG', name: "Republic Of Congo")
Country.create(code: 'CH', name: "Switzerland")
Country.create(code: 'CL', name: "Chile")
Country.create(code: 'CN', name: "China")
Country.create(code: 'CO', name: "Colombia")
Country.create(code: 'CR', name: "Costa Rica")
Country.create(code: 'CV', name: "Cape Verde")
Country.create(code: 'CY', name: "Cyprus")
Country.create(code: 'CZ', name: "Czech Republic")
Country.create(code: 'DE', name: "Germany")
Country.create(code: 'DK', name: "Denmark")
Country.create(code: 'DM', name: "Dominica")
Country.create(code: 'DO', name: "Dominican Republic")
Country.create(code: 'DZ', name: "Algeria")
Country.create(code: 'EC', name: "Ecuador")
Country.create(code: 'EE', name: "Estonia")
Country.create(code: 'EG', name: "Egypt")
Country.create(code: 'ES', name: "Spain")
Country.create(code: 'FI', name: "Finland")
Country.create(code: 'FJ', name: "Fiji")
Country.create(code: 'FM', name: "Federated States Of Micronesia")
Country.create(code: 'FR', name: "France")
Country.create(code: 'GB', name: "United Kingdom")
Country.create(code: 'GD', name: "Grenada")
Country.create(code: 'GH', name: "Ghana")
Country.create(code: 'GM', name: "Gambia")
Country.create(code: 'GR', name: "Greece")
Country.create(code: 'GT', name: "Guatemala")
Country.create(code: 'GW', name: "Guinea-Bissau")
Country.create(code: 'GY', name: "Guyana")
Country.create(code: 'HK', name: "Hong Kong")
Country.create(code: 'HN', name: "Honduras")
Country.create(code: 'HR', name: "Croatia")
Country.create(code: 'HU', name: "Hungary")
Country.create(code: 'ID', name: "Indonesia")
Country.create(code: 'IE', name: "Ireland")
Country.create(code: 'IL', name: "Israel")
Country.create(code: 'IN', name: "India")
Country.create(code: 'IS', name: "Iceland")
Country.create(code: 'IT', name: "Italy")
Country.create(code: 'JM', name: "Jamaica")
Country.create(code: 'JO', name: "Jordan")
Country.create(code: 'JP', name: "Japan")
Country.create(code: 'KE', name: "Kenya")
Country.create(code: 'KG', name: "Kyrgyzstan")
Country.create(code: 'KH', name: "Cambodia")
Country.create(code: 'KN', name: "St. Kitts and Nevis")
Country.create(code: 'KR', name: "Republic Of Korea")
Country.create(code: 'KW', name: "Kuwait")
Country.create(code: 'KY', name: "Cayman Islands")
Country.create(code: 'KZ', name: "Kazakstan")
Country.create(code: 'LA', name: "Lao People’s Democratic Republic")
Country.create(code: 'LB', name: "Lebanon")
Country.create(code: 'LC', name: "St. Lucia")
Country.create(code: 'LK', name: "Sri Lanka")
Country.create(code: 'LR', name: "Liberia")
Country.create(code: 'LT', name: "Lithuania")
Country.create(code: 'LU', name: "Luxembourg")
Country.create(code: 'LV', name: "Latvia")
Country.create(code: 'MD', name: "Republic Of Moldova")
Country.create(code: 'MG', name: "Madagascar")
Country.create(code: 'MK', name: "Macedonia")
Country.create(code: 'ML', name: "Mali")
Country.create(code: 'MN', name: "Mongolia")
Country.create(code: 'MO', name: "Macau")
Country.create(code: 'MR', name: "Mauritania")
Country.create(code: 'MS', name: "Montserrat")
Country.create(code: 'MT', name: "Malta")
Country.create(code: 'MU', name: "Mauritius")
Country.create(code: 'MW', name: "Malawi")
Country.create(code: 'MX', name: "Mexico")
Country.create(code: 'MY', name: "Malaysia")
Country.create(code: 'MZ', name: "Mozambique")
Country.create(code: 'NA', name: "Namibia")
Country.create(code: 'NE', name: "Niger")
Country.create(code: 'NG', name: "Nigeria")
Country.create(code: 'NI', name: "Nicaragua")
Country.create(code: 'NL', name: "Netherlands")
Country.create(code: 'NO', name: "Norway")
Country.create(code: 'NP', name: "Nepal")
Country.create(code: 'NZ', name: "New Zealand")
Country.create(code: 'OM', name: "Oman")
Country.create(code: 'PA', name: "Panama")
Country.create(code: 'PE', name: "Peru")
Country.create(code: 'PG', name: "Papua New Guinea")
Country.create(code: 'PH', name: "Philippines")
Country.create(code: 'PK', name: "Pakistan")
Country.create(code: 'PL', name: "Poland")
Country.create(code: 'PT', name: "Portugal")
Country.create(code: 'PW', name: "Palau")
Country.create(code: 'PY', name: "Paraguay")
Country.create(code: 'QA', name: "Qatar")
Country.create(code: 'RO', name: "Romania")
Country.create(code: 'RU', name: "Russia")
Country.create(code: 'SA', name: "Saudi Arabia")
Country.create(code: 'SB', name: "Solomon Islands")
Country.create(code: 'SC', name: "Seychelles")
Country.create(code: 'SE', name: "Sweden")
Country.create(code: 'SG', name: "Singapore")
Country.create(code: 'SI', name: "Slovenia")
Country.create(code: 'SK', name: "Slovakia")
Country.create(code: 'SL', name: "Sierra Leone")
Country.create(code: 'SN', name: "Senegal")
Country.create(code: 'SR', name: "Suriname")
Country.create(code: 'ST', name: "Sao Tome and Principe")
Country.create(code: 'SV', name: "El Salvador")
Country.create(code: 'SZ', name: "Swaziland")
Country.create(code: 'TC', name: "Turks and Caicos")
Country.create(code: 'TD', name: "Chad")
Country.create(code: 'TH', name: "Thailand")
Country.create(code: 'TJ', name: "Tajikistan")
Country.create(code: 'TM', name: "Turkmenistan")
Country.create(code: 'TN', name: "Tunisia")
Country.create(code: 'TR', name: "Turkey")
Country.create(code: 'TT', name: "Trinidad and Tobago")
Country.create(code: 'TW', name: "Taiwan")
Country.create(code: 'TZ', name: "Tanzania")
Country.create(code: 'UA', name: "Ukraine")
Country.create(code: 'UG', name: "Uganda")
Country.create(code: 'US', name: "United States")
Country.create(code: 'UY', name: "Uruguay")
Country.create(code: 'UZ', name: "Uzbekistan")
Country.create(code: 'VC', name: "St. Vincent and The Grenadines")
Country.create(code: 'VE', name: "Venezuela")
Country.create(code: 'VG', name: "British Virgin Islands")
Country.create(code: 'VN', name: "Vietnam")
Country.create(code: 'YE', name: "Yemen")
Country.create(code: 'ZA', name: "South Africa")
Country.create(code: 'ZW', name: "Zimbabwe")
